---
driver:
  name: docker
  #require_chef_omnibus: true

provisioner:
  name: chef_solo
  cookbooks_path:
    - ./cookbooks

platforms:
  #mknod on docker ubuntu that gets pulled in by java is not happy
  #- name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[jenkins-config::default]
    attributes:
      jenkins:
        master:
          jvm_options: '-Djenkins.install.runSetupWizard=false'